# Site settings
title: Nasrudin Bin Salim
twitter_username: spionasrudin
LinkedIn_Link: https://www.linkedin.com/in/nasrudin-salim/
name: Nasrudin Salim
baseurl: ''

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: LinkedIn
   url: https://www.linkedin.com/in/nasrudin-salim/
 - title: GitHub
   url: https://github.com/Nasdin/
 - title: Kaggle
   url: https://www.kaggle.com/nasdin
 - title: Blog
   url: http://Blog.NasrudinSalim.com
 - title: <strong>Contact</strong>
   url: mailto:Nas@NasrudinSalim.com

profile:
  yourface: ./img/profile.jpeg
  goal: Striving to be a global expert in Data Science and Artificial Intelligence
  somequote: I am always striving to improve myself one way or another, stemming from an inner insecurity about never knowing enough
#  age: 24
  availability: I'm available and on the hunt for new opportunities for growth!
  contact: <a href="mailto:Nas@NasrudinSalim.com?Subject=I%20Want%20To%20Hire%20You" target="_top">Nas@NasrudinSalim.com</a></p>
  resume:

#Any buzzword skills you want to include
skillset1:
 - Python
 - C++
 - VB/VBA
 - MQL5
 - Databases
 - AWS
skillset2:
 - Machine Learning
 - Artificial Intelligence (AI)
 - Data Science
 - Big Data
 - Algorithms
 - Deep Learning
 - Bayesian Modelling and Probabilistic models
 - Reinforcement Learning
skillset3:
 - Financial Markets Trading
 - Quantitative Hedge Fund
 - Portfolio Management
skillset4:
 - Hadoop
 - Spark
 - Git & Docker
 - Startups

##List of people to mention
#people:
#  - person: Linh Ha, fuulin.com
#    website: http://fuulin.com
#    title: Creative Designer, Criteo.



#Work experience is required
roles:
 - title: Lead Data Scientist <br> <br> Co-Founder & COO
   start: 2014 May
   end: Ongoing
   employer: <a href="https://www.Chatoyance.org" target='_blank'>Chatoyance Capital Management</a> <br/> <br/> Singapore &  <br/> United States, Boston.
   description: Deep fintech startup providing A.I. and machine learning tools to augment/replace over a fund or for everyday investors to independently match up in competency against entire funds or prop firms.<br><br>Chatoyance Zeus Reinforcement Learning AI, self-generates trading rules & strategies with PCL built with Python & Tensorflow.<br><br>Chatoyance Trading Group - Group Master-Master copier service with UI/UX, stats and user database with web interface, made with mql4 and Django.<br><br>Time-Series prediction of market trend and price direction using LSTMs, gradient boosting and prophet on Python. Served as analytics subscription product to traders & funds.<br><br>Risk AI - Obtain optimum risk strategy and each risk per trade using volatility, unsupervised learning and predicted trade outcome.<br><br>Sentiment analysis - Using NLP on twitter, bloomberg and forex calendar API, web-scraping to determine sentiment.

 - title: Data Scientist <br><br> CIO
   start: 2017 Feb
   end: 2018 Jan
   employer: <a href="http://www.liquiditymagnate.com" target='_blank'>Liquidity Magnate</a>,<br/> <a href="http://wanchatdotcom.com/" target='_blank'>WanChat</a>,<br/> <a href="http://vip-queue.com" target='_blank' >VIPQueue</a>,<br/><a href="https://eventpenguins.com" target='_blank' >Event Penguins</a> <br/> <br/> Malaysia, Shah Alam
   description: Trained team of manual traders on trading strategies, technical, fundamental, sentiment, wave theory analysis.<br><br>Built indicators for trading team, volume tick analysis and spread analysis indicators on MQL4.<br><br>Provided quant algorithmic strategy, rule-based trading with Neural nets & technical analysis, supervised learning with an online-learning component, updates probability tables of binary market patterns and trade decisions for each market move and trade closed, on MQL5.<br><br>Created a Risk Management and countertrade supervised learning AI system using machine predicted trade outcomes to automatically hedge, providing stable returns while providing constant volume rebates without the danger of martingale.<br><br>Supported on product and project management of dev teams surrounding EventPenguins, VipQueue & WanChat.<br><br>Achieved investment banking license for the region & regulation & licensed to work as a fintech provider cum liquidity provider<br><br>Responsible for the backbone of tech operations, provide a fixed 40% net return annually for investors with data science informed decisions, manual & quant trading and revenue streams from fintech products.

 - title: Software Engineer
   start: 2016 Sep
   end: 2017 Sep
   employer: SkillTec Pte. Ltd, UTETech Sdn. Bhd. <br><br/> Singapore
   description: Automated tasks and routines with VBA & C++ and created internal software products for engineers and clerks.<br><br>Planned and created software integrating with google spreadsheet API to create user-friendly relational databases.<br><br>Built an internal project management and tracking software to synchronize workflow with a simple web UI for input and overview.

 - title: Batallion IT Expert <br><br> Military Service
   start: 2014 Sep
   end: 2016 Sep
   employer: Singapore Armed Forces , <br/> <br/> Singapore
   description: Title and position conferred to me.<br><br>Worked on VBA projects at the company, batallion and formation level. Created macros and analysis with excel, VBA and Access. <br><br> Worked with project officers on confidential military projects. <br/><br/> I worked on confidential military projects to augment, optimize and plan new formations, divisions as well as create generators in VBA for manpower optimization and work schedules. Automated reports condensed days long task into minutes.
 - title: Consultant (Freelance)
   start: 2011 Jan
   end: 2014 Sep
   employer: Jerick Technologies<br/>Jovan Technologies<br/>Arnet Bernard Investment Group LLC <br/>Golden Zone Trading LLC<br/><br/> Singapore <br/> Indonesia <br/> United States
   description: At 17, headhunted & consulted by managers in Singapore,  sent on paid overseas trips to Indonesia. Provided full satisfactory deliverables, code & presentation within a week, on VBA,  Excel & Google API. Solutions still used to this day.<br><br>Worked in cross-culture environment overseas in multiple companies as a consultant<br><br>Provided winning solutions to financial education trading companies which boosted customer growth by 30%, automated report & portfolio tracking creation. Client companies converted to recurring customers.

 - title: Analyst (Intern)
   start: 2013 Sep
   end: 2014 Feb
   employer: ST Kinetics , Singapore<br/><br/> Republic Polytechnic Research Branch.
   description: Data Scraping and analysis. Analyzed samples with Excel VBA, Pivot Tables and a proprietary company software. <br> <br/> Automated the process with simple excel VBA loops and advanced excel functions. Created SOP which was later adopted by department.
 - title: Proprietary Trader
   start: 2011 Aug
   end: 2014 May
   employer: Self-Employed
   description: Accumulated more than 10,000 hours of on-screen chart analyzing time. Started and am a philomath since 14 years old.<br><br>At 17, have conducted classes to teach financial trading to adults with personal mentorship on technical and wave analysis.<br><br>At 18, traded & managed small funds of 4 figures & 5 figures for clients before founding & working for CCM & LM


#Accomplishments, Awards, References and Testimonials
Accomplishment:
 - award: Top Performer of Data Science Immersive Professional Course
   description: Was the top performing data scientist amongst professionals and managers in General Assembly's Data Science full-time immersive programme. <br><br> Presented my work to minister assoc prof Dr. Yaacob Ibrahim.
 - award: Module Prize in Stem Cell and Tissue Engineering
   description: Award to top student in cohort
 - award: Anugerah Khas Mendaki
   description: Graduated as one of the top students in the national level and one of the top muslim students in Singapore.
 - award: Academic Roll of Honours throughout college
   description: Continuously attaining Top 5% of entire cohort in college
 - award:  Director's Roll of Honours throughout college
   description: Continuously attaining Top 10% of entire cohort in college.

References:
 - Human:
    Name: Daniel Shea
    Title: CEO & Founder
    Company: Chatoyance Capital Management Pte. Ltd.
    Contact: Dshea@Chatoyance.org
 - Human:
    Name: Ting Tse Xiong
    Title: Director
    Company: Skilltec Pte. Ltd & UteTec Pte. Ltd
    Contact: Tsexiong@Skilltec.com.sg

 - Human:
    Name: Rizwan Ramalan
    Title: President, CEO
    Company: LiquidityMagnate Sdn Bhd group of companies
    Contact: +60 17-666 0167

 - Human:
    Name: Woo Chun Onn
    Title: VP
    Company: Chatoyance Capital Management
    Contact: Cowoo@chatoyance.org

Quote:
 - Human:
    Name: Dr Ricky Chua
    Title: Lecturer, President NTU MSE Alumni Association
    Quote: I feel that Nasrudin is extraordinarily bright and needs to be given the right team to bring out his social side.
    Contact: Available upon request




#Languages
literalLanguages:
 - language: English
   Ability: Fluent & Native
 - language: Malay
   Ability: Fluent & Native
 - language: Indonesian
   Ability: Fluent
 - language: Chinese Mandarin
   Ability: Basic conversational

#Education is required
education:
 - level: Data Science Immersive
   date: 2017 Nov
   subject: <a href= https://generalassemb.ly/education/data-science-immersive> Data Science Immersive Programme</a>, <br/> Sponsorship from IMDA, IMTalent Program <br/><br/> First locally and professionally trained Data Scientist batch in Singapore
   link: https://generalassemb.ly/
   school: General Assembly
 - level: Bachelor(hons) of Engineering
   date: 2017 June  <br/><br/> (Left in Y3 to Pursue passion in programming and Data Science)
   subject: Materials Engineering with a minor in Business
   link: https://www.topuniversities.com/universities/nanyang-technological-university-singapore-ntu
   school: Nanyang Technological University, Singapore
 - level: Polytechnic Diploma
   date: 2014 May
   subject: Materials Science. <br/><br/>FYP in Thermal Interface Material â€“ HDPE, copper compositeT<br/>hermally Conductive Polymer Composite For High Power Electronic Devices
   link: http://www.rp.edu.sg
   school: Republic Polytechnic, Singapore

#This section is optional (as is the image link below), should come with a certificate.
selfeducation:
 - provider: Coursera
   profileurl: https://www.coursera.org/user/fa78571af5e38932c8e2ce196bb3e0fc
   courses:
   - title: Deep Learning Specialisation (WIP)
     link: https://www.coursera.org/specializations/deep-learning
     cert: https://www.coursera.org/specializations/deep-learning
   - title: Neural Networks & Deep Learning (WIP )
     link: https://www.coursera.org/learn/neural-networks-deep-learning
     cert:
   - title: Improving Deep Neural Networks (WIP)
     link: https://www.coursera.org/learn/deep-neural-network
     cert:
   - title: Structuring Machine Learning Projects (WIP)
     link: https://www.coursera.org/learn/machine-learning-projects
     cert:
   - title: Convolutional Neural Networks (WIP)
     link: https://www.coursera.org/learn/convolutional-neural-networks
     cert:
   - title: NLP Sequence Models (WIP)
     link: https://www.coursera.org/learn/nlp-sequence-models
     cert:
 - provider: DataCamp
   profileurl: https://www.datacamp.com/profile/nasrudinsalimsuden
   courses:
   - title: Python for Data Science
     link: https://www.datacamp.com/courses/intro-to-python-for-data-science
     cert: ./cert/DataCamp/Intro_Python.pdf
   - title: Intermediate Python for Data Science
     link: https://www.datacamp.com/courses/intermediate-python-for-data-science
     cert: ./cert/DataCamp/Intermediate_Python.pdf
   - title: Importing Data to Python Level 1
     link: https://www.datacamp.com/courses/importing-data-in-python-part-1
     cert: ./cert/DataCamp/Importing_Data_1.pdf
   - title: Importing Data to Python Level 2
     link: https://www.datacamp.com/courses/importing-data-in-python-part-2
     cert: ./cert/DataCamp/Importing_Data_2.pdf
   - title: Statistical Thinking In Python Level 1
     link: https://www.datacamp.com/courses/statistical-thinking-in-python-part-1
     cert: ./cert/DataCamp/Statistical_Thinking_Python_1.pdf
   - title: Statistical Thinking In Python Level 2
     link: https://www.datacamp.com/courses/statistical-thinking-in-python-part-2
     cert: ./cert/DataCamp/Statistical_Thinking_Python_2.pdf

 - provider: StackSkills
   profileurl: https://stackskills.com
   courses:
   - title: "The Complete Python Course: Beginner to Advanced"
     link: https://stackskills.com/p/python-complete
     cert:
   - title: "JavaScript Programming Complete"
     link: https://stackskills.com/p/javascript-complete
     cert:
   - title: "Google's Go (golang) Programming Language"
     link: https://stackskills.com/p/learn-how-to-code
     cert:
   - title: "Learn By Example: Scala"
     link: https://stackskills.com/p/learn-by-example-scala
     cert:
   - title: "How to Make a Freaking iPhone App - iOS 10 and Swift 3"
     link: https://stackskills.com/p/how-to-make-a-freaking-iphone-app-ios-10-and-swift-3
     cert:
   - title: "Professional Rails Code Along"
     link: https://stackskills.com/p/professional-rails-code-along
     cert:
   - title: "Git Complete Mastery with GitHub : 100% Hands-on Git Guide"
     link: https://stackskills.com/p/git-complete-mastery-github-100-hands-on-2016-git-guide
     cert:
   - title: Learn Angular 2 from Beginner to Advanced
     link: https://stackskills.com/p/learn-angular-2-from-beginner-to-advanced
     cert:
   - title: Projects in Programming Languages - Ruby, Python, Java
     link: https://stackskills.com/p/projects-in-programming-languages-ruby-python-java
     cert:

 - provider: Nanyang Technological University
   profileurl: https://www.topuniversities.com/universities/nanyang-technological-university-singapore-ntu
   courses:
   - title: Engineering Mathematics
     cert: ./cert/NTUEngineeringMathematics.jpeg



#List of interesting Github repo/projects to include - optional
github:
 - Nasdin/ReinforcementLearning-AtariGame
 - Nasdin/Burning-Cars-ImageRecognition-realtime
 - Nasdin/Property-Arbitrage-Prediction-Strategy
 - Nasdin/Predicting-Salaries-Indeed.com-AutoML
 - Nasdin/Predicting-Mosquito-Hotspots
 - Nasdin/Drone-Strike-Visualization
 - Nasdin/kaggle-competitions-nasdin
 - ASAAI/speech2text
 - Nasdin/AISaturdayTutorials
 - Nasdin/Stacked-Autoencoders-Financial-Trading

#A bit important outside involvements
importantactivities:
 - Title: Volunteer and Humanitarian Aid
   StartYear: 2015 Jan
   EndYear: Ongoing
   Description: Independently volunteer on own time and expense <br/> Trusted with collection of new and used goods and monies on a weekly basis. Sent as aid to 3rd world countries through established trustworthy contacts.

 - Title: Overseas Humanitarian Volunteering (On-Ground)
   StartYear: 2014 Jan
   EndYear: 2016 Sep
   Description: Self-sponsored, on my own expense and time. <br/> Liaised with mosques to collect clothes, aid and goods. <br/> Self-Funded projects with family, Building Mosque, Wells, Water Pump/plumbing facilities, irrigation, Canteen, Orphanage and shelter for mentally ill


#Other less important Involvements
notimportantactivities:
 - Title: Listed in World Genius Directory
   link: http://psiq.org/
   cert: ./cert/HighIQCerts/WGDNASRUDINSALIM.jpg

 - Title: International High IQ Society ( Top 5% )
   link: https://www.ihiqs.org/
   cert: ./cert/HighIQCerts/IHIQS.jpg

 - Title: Mensa ( Top 1% )
   link: http://www.mensa.org
   cert: ./cert/HighIQCerts/Mensaletter.png

 - Title: Tensa ( Top 10% )
   link: http://www.teniq.com/
   cert: ./cert/HighIQCerts/Tensa.jpg

 - Title: The High Intellect IQ Society ( Top 2% )
   link: http://www.thisiqsociety.org/
   cert: ./cert/HighIQCerts/THIS.jpg

 - Title: TORR IQ Society ( Top 0.13% )
   link: http://www.torr.org/
   cert: ./cert/HighIQCerts/TORR.jpg

 - Title: UberIQ ( Top 0.13% )
   link: http://www.uberiq.org/
   cert: ./cert/HighIQCerts/UberIQ.jpg

#Kaggle Flair
#kaggle:
# profile: https://www.kaggle.com/nasdin
# picture: https://kaggle2.blob.core.windows.net/avatars/images/1248604-kg.jpg
# kagglerankpicture: ./img/kagglerank.png
# kagglerank: Contributor
# competitions:
#    - title: Titanic Prediction
#      link: https://www.kaggle.com/c/titanic
#      rank: Top 1%, out of 8300
#    - title:
#      link:
#      rank:


#Stackoverflow flair is optional
#stackoverflow:
#  profileurl: http://stackoverflow.com/users/258813/rhinds
#  flairimageurl: http://stackoverflow.com/users/flair/258813.png

#Mobile apps section is optional
#apps:
# - name: Chuck the Quiz
#   platform: Android
#   url: https://play.google.com/store/apps/details?id=com.tmm.android.chuck&feature=search_result#?t=W251bGwsMSwxLDEsImNvbS50bW0uYW5kcm9pZC5jaHVjayJd
#   description: A basic early Android app (open sourced)

#Contact Information


#An additional info freetext section is optional at the bottom of the page - can be text or HTML
#additionalinfo: |

#theme: jekyll-theme-minimal
